// <auto-generated />
using System;
using LearningBank.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningBank.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LearningBankDbContext))]
    [Migration("20260529005721_AddTaskCategory")]
    partial class AddTaskCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("LearningBank.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<Guid>("ActorId");

                    b.Property<string>("After");

                    b.Property<string>("Before");

                    b.Property<Guid>("EntityId");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTimeOffset>("OccurredAt");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<bool>("IsArchived");

                    b.Property<bool>("IsChildAllowed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.ChildLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ChildId");

                    b.Property<DateTimeOffset>("LinkedAt");

                    b.Property<Guid>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId", "ChildId")
                        .IsUnique();

                    b.ToTable("ChildLinks");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.LearningTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CategoryId");

                    b.Property<Guid>("ChildId");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<Guid>("CreatedByParentId");

                    b.Property<string>("DaysOfWeekCsv")
                        .HasMaxLength(64);

                    b.Property<DateTime?>("EndDateUtc");

                    b.Property<int?>("Frequency");

                    b.Property<bool>("IsActive");

                    b.Property<int?>("MaxOccurrences");

                    b.Property<decimal>("MonetaryValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RecurrenceType");

                    b.Property<DateTime>("StartDateUtc");

                    b.Property<int>("TargetAccount");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ChildId", "IsActive");

                    b.ToTable("LearningTasks");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.TaskCompletion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ChildId");

                    b.Property<DateTimeOffset>("CompletedByChildAt");

                    b.Property<DateTime>("OccurrenceDateUtc");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500);

                    b.Property<DateTimeOffset?>("ReviewedAt");

                    b.Property<Guid?>("ReviewedByParentId");

                    b.Property<int>("Status");

                    b.Property<Guid>("TaskId");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "Status");

                    b.HasIndex("TaskId", "OccurrenceDateUtc", "Status");

                    b.ToTable("TaskCompletions");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Account");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("CategoryId");

                    b.Property<Guid>("ChildId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<Guid?>("EnteredByParentId");

                    b.Property<DateTimeOffset>("PostedAt");

                    b.Property<Guid?>("RelatedTransactionId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PostedAt");

                    b.HasIndex("ChildId", "Account");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.TransferRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ChildId");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTimeOffset>("RequestedAt");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500);

                    b.Property<DateTimeOffset?>("ReviewedAt");

                    b.Property<Guid?>("ReviewedByParentId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "Status");

                    b.ToTable("TransferRequests");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<bool>("IsActive");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Role");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId", "Provider")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.ChildLink", b =>
                {
                    b.HasOne("LearningBank.Domain.Entities.User", "Child")
                        .WithMany("ParentLinks")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearningBank.Domain.Entities.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.LearningTask", b =>
                {
                    b.HasOne("LearningBank.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LearningBank.Domain.Entities.User", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.TaskCompletion", b =>
                {
                    b.HasOne("LearningBank.Domain.Entities.LearningTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("LearningBank.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LearningBank.Domain.Entities.User", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.TransferRequest", b =>
                {
                    b.HasOne("LearningBank.Domain.Entities.User", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("LearningBank.Domain.Entities.User", b =>
                {
                    b.Navigation("ParentLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
